(function(){
'use strict';
const root=document.getElementById('rescene-record'),$=id=>root.querySelector('#'+id),db=JSON.parse($('rr-data').textContent),svg=$('mts-chart');
const types=[['top100','TOP100','시간봉'],['hot100-d30','HOT100 · 30일','시간봉'],['hot100-d100','HOT100 · 100일','시간봉'],['daily','일간','일봉'],['weekly','주간','주봉'],['monthly','월간','월봉'],['yearly','연간','연봉']],songs=db.manifest.songs;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=s=>songs.filter(x=>x.name===s.name).length>1?s.name+' · '+s.album:s.name;
let type='daily',songId=null,bars=[],start=0,span=100,geometry={},pointers=new Map(),gesture=null;
const unit=()=>types.find(x=>x[0]===type)[2];
function clamp(a,n){const length=Math.max(1,bars.length);n=Math.max(Math.min(8,length),Math.min(length,n));start=Math.max(0,Math.min(length-n,a));span=n;}
function reset(){const n=svg.getBoundingClientRect().width<500?40:100;clamp(bars.length-n,n);draw();}
function consecutive(a,b){const u=unit();if(u==='월봉'||u==='연봉'){const aa=a.slice(0,10),bb=b.slice(0,10),year=Number(bb.slice(0,4))-Number(aa.slice(0,4));return u==='연봉'?year===1:year*12+Number(bb.slice(5,7))-Number(aa.slice(5,7))===1;}const parse=t=>Date.parse(t+(t.length===10?'T00:00:00':'')+'+09:00');return parse(b)-parse(a)===({시간봉:3600000,일봉:86400000,주봉:604800000}[u]);}
function load(){const data=db.charts[type],eligible=songs.filter(s=>Object.entries(data.songs[s.id]||{}).some(([time,p])=>time>=db.manifest.debut&&Number.isFinite(p.rank)&&p.rank>0));if(!eligible.some(s=>s.id===songId))songId=eligible[0]?.id??null;
$('mts-song').innerHTML=eligible.map(s=>'<option value="'+s.id+'"'+(s.id===songId?' selected':'')+'>'+esc(name(s))+'</option>').join('');$('mts-song').disabled=!eligible.length;
bars=Object.entries(data.songs[songId]||{}).filter(([time])=>time>=db.manifest.debut).sort((a,b)=>a[0].localeCompare(b[0])).map(([time,p])=>({time,rank:Number.isFinite(p.rank)&&p.rank>0?p.rank:null,status:p.status})).map((b,i,all)=>({...b,open:i>0&&all[i-1].rank!=null&&consecutive(all[i-1].time,b.time)?all[i-1].rank:null}));
$('mts-unit').textContent=unit();$('mts-title').textContent=eligible.length?name(eligible.find(s=>s.id===songId)):'진입 기록 없음';$('mts-chart-label').textContent=types.find(x=>x[0]===type)[1];
$('mts-latest').textContent=bars.at(-1)?.rank!=null?bars.at(-1).rank+'위':'범위 밖 / 기록 없음';
$('mts-note').textContent='1봉 = 1'+({시간봉:'시간',일봉:'일',주봉:'주',월봉:'월',연봉:'년'}[unit()])+' 집계. 시가 = 직전 집계 순위 · 종가 = 해당 집계 순위. 빨강은 순위 상승, 파랑은 하락입니다. 직전 집계 순위가 없으면 단일 순위로 표시합니다.';
pointers.clear();gesture=null;reset();}
function draw(){const w=Math.max(220,svg.getBoundingClientRect().width||800),h=w<500?300:360,left=48,right=52,top=18,bottom=36,pw=w-left-right,ph=h-top-bottom;svg.setAttribute('viewBox','0 0 '+w+' '+h);$('mts-tooltip').hidden=true;
const first=Math.max(0,Math.floor(start)),last=Math.min(bars.length,Math.ceil(start+span)),visible=bars.slice(first,last),values=visible.filter(b=>b.rank!=null).flatMap(b=>b.open==null?[b.rank]:[b.open,b.rank]),fixed=type==='top100'||type.startsWith('hot100-');let lo=values.length?Math.max(1,Math.floor((Math.min(...values)-5)/10)*10):1,hi=values.length?Math.ceil((Math.max(...values)+5)/10)*10:120;if(fixed){lo=1;hi=100;}else{lo=Math.min(lo,90);hi=Math.max(hi,110);}const expanded=$('rr-expand').checked;if(expanded)lo=1;const scale=r=>expanded?Math.log(Math.max(1,r)):r;svg.dataset.rankScale=expanded?'expanded':'linear';const x=i=>left+(i-start+.5)*pw/span,y=r=>top+(scale(r)-scale(lo))/(scale(hi)-scale(lo))*ph;
geometry={w,h,left,right,top,bottom,pw,ph,x,y};svg.dataset.start=String(start);svg.dataset.span=String(span);
let html='<title>'+esc(unit())+' · '+esc($('mts-title').textContent)+'</title><defs><clipPath id="mts-clip"><rect x="'+left+'" y="'+top+'" width="'+pw+'" height="'+ph+'"/></clipPath></defs>';
for(const v of (expanded?(fixed?[1,2,4,6,10,20,40,60,80,100]:[1,2,4,6,10,20,50,100,250,500,1000].filter(v=>v<=hi)):(fixed?[1,20,40,60,80,100]:Array.from({length:5},(_,i)=>Math.round(lo+(hi-lo)*i/4))))){html+='<line x1="'+left+'" x2="'+(w-right)+'" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#27313e"/><text x="'+(w-right+8)+'" y="'+(y(v)+4)+'" fill="#94a3b8" font-size="11">'+v+'</text>';}
if(!fixed)html+='<line id="mts-top100-line" x1="'+left+'" x2="'+(w-right)+'" y1="'+y(100)+'" y2="'+y(100)+'" stroke="#f472a5" stroke-width="3"/><text x="'+(left+4)+'" y="'+(y(100)-6)+'" fill="#f472a5" font-size="11">100위 진입선</text>';
html+='<g clip-path="url(#mts-clip)">';
for(let i=first;i<last;i++){const b=bars[i];if(b.rank==null)continue;const open=b.open??b.rank,color=b.open==null||b.rank===open?'#a6b2c4':b.rank<open?'#ff5470':'#49a3ff',bw=Math.max(1,Math.min(18,pw/span*.8)),height=Math.max(2.4,Math.abs(y(open)-y(b.rank))),bodyTop=open===b.rank?y(b.rank)-1.2:Math.min(y(open),y(b.rank));html+='<rect data-bar-time="'+b.time+'" data-rank="'+b.rank+'" data-open="'+(b.open??'')+'" data-close="'+b.rank+'" x="'+(x(i)-bw/2)+'" y="'+bodyTop+'" width="'+bw+'" height="'+height+'" fill="'+color+'"/>';}
html+='</g>';if(!values.length)html+='<text x="'+(w/2)+'" y="170" text-anchor="middle" fill="#94a3b8" font-size="13">이 구간에 확인된 순위가 없습니다</text>';
for(let n=0;n<3;n++){const i=Math.min(bars.length-1,Math.max(0,Math.round(start+(span-1)*n/2))),b=bars[i];if(!b)continue;html+='<text x="'+(n===0?left:n===2?w-right:(left+pw/2))+'" y="'+(h-12)+'" text-anchor="'+(n===0?'start':n===2?'end':'middle')+'" fill="#94a3b8" font-size="11">'+esc(type.includes('100')?b.time.slice(5,10)+' '+b.time.slice(11,16):b.time.slice(0,10))+'</text>';}
svg.innerHTML=html+'<g id="mts-rank-guide"></g><line id="mts-guide" x1="0" x2="0" y1="'+top+'" y2="'+(h-bottom)+'" stroke="#cbd5e1" visibility="hidden"/>';
$('mts-range').textContent=bars.length?(bars[first]?.time.replace('T',' ')||'')+' — '+(bars[Math.max(first,last-1)]?.time.replace('T',' ')||'')+' KST':'기록 없음';}
function inspect(e){if(!bars.length)return;const rect=svg.getBoundingClientRect(),g=geometry,xx=e.clientX-rect.left,i=Math.min(bars.length-1,Math.max(0,Math.floor(start+(xx-g.left)/g.pw*span))),b=bars[i],tip=$('mts-tooltip');tip.innerHTML='<b>'+esc(b.time.replace('T',' '))+' KST · '+unit()+'</b><div>'+esc($('mts-title').textContent)+' <strong>'+(b.rank!=null?b.rank+'위':b.status==='out'?'집계 범위 밖':'기록 없음')+'</strong></div>'+(b.rank!=null?'<small>시가 '+(b.open==null?'기록 없음':b.open+'위')+' · 종가 '+b.rank+'위</small>':'');tip.hidden=false;const guide=$('mts-guide');guide.setAttribute('x1',g.x(i));guide.setAttribute('x2',g.x(i));guide.setAttribute('visibility','visible');$('mts-rank-guide').innerHTML=b.rank==null?'':'<line x1="'+g.left+'" x2="'+g.x(i)+'" y1="'+g.y(b.rank)+'" y2="'+g.y(b.rank)+'" stroke="#ff7187" stroke-dasharray="4 3"/><rect x="0" y="'+(g.y(b.rank)-10)+'" width="44" height="20" rx="3" fill="#b52c50"/><text x="22" y="'+(g.y(b.rank)+4)+'" text-anchor="middle" font-size="11" fill="white">'+b.rank+'위</text>';}
function zoom(factor,anchor=.5){const next=span*factor;clamp(start+span*anchor-next*anchor,next);draw();}
svg.addEventListener('wheel',e=>{e.preventDefault();const delta=e.deltaY||e.deltaX;if(!delta)return;if(e.ctrlKey){const g=geometry,rect=svg.getBoundingClientRect(),anchor=Math.max(0,Math.min(1,(e.clientX-rect.left-g.left)/g.pw));zoom(Math.exp(Math.max(-1,Math.min(1,delta*.003))),anchor);}else{clamp(start+Math.sign(delta)*Math.max(1,span*.1),span);draw();}},{passive:false});
function beginGesture(){const points=[...pointers.values()],rect=svg.getBoundingClientRect();if(points.length===1)gesture={kind:'drag',x:points[0].x,start,span};else if(points.length===2)gesture={kind:'pinch',distance:Math.max(1,Math.hypot(points[1].x-points[0].x,points[1].y-points[0].y)),anchor:((points[0].x+points[1].x)/2-rect.left-geometry.left)/geometry.pw,start,span};}
svg.onpointerdown=e=>{if(e.pointerType==='touch')return;if(e.button!=null&&e.button!==0)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});svg.setPointerCapture?.(e.pointerId);beginGesture();};
svg.onpointermove=e=>{if(e.pointerType==='touch')return;if(!pointers.has(e.pointerId)){inspect(e);return;}e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const pts=[...pointers.values()];if(pts.length===1&&gesture?.kind==='drag'){clamp(gesture.start-(e.clientX-gesture.x)/geometry.pw*gesture.span,gesture.span);draw();}else if(pts.length===2&&gesture?.kind==='pinch'){const distance=Math.max(1,Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y)),rect=svg.getBoundingClientRect(),center=((pts[0].x+pts[1].x)/2-rect.left-geometry.left)/geometry.pw,next=gesture.span*gesture.distance/distance;clamp(gesture.start+gesture.anchor*gesture.span-center*next,next);draw();}};
function finish(e){if(e.pointerType==='touch')return;const tap=gesture?.kind==='drag'&&Math.abs(e.clientX-gesture.x)<4;pointers.delete(e.pointerId);svg.releasePointerCapture?.(e.pointerId);if(pointers.size)beginGesture();else gesture=null;if(tap)inspect(e);}
svg.onpointerup=finish;svg.onpointercancel=e=>{pointers.delete(e.pointerId);gesture=null;};svg.onpointerleave=e=>{if(!pointers.size&&e?.pointerType!=='touch'){$('mts-rank-guide').innerHTML='';$('mts-tooltip').hidden=true;$('mts-guide')?.setAttribute('visibility','hidden');}};
// Native touch handlers take priority over browser pinch, including Safari.
const touchArea=svg.parentElement,desk=$('mts-desk');
function syncTouches(e){pointers.clear();for(const t of Array.from(e.touches))pointers.set(t.identifier,{x:t.clientX,y:t.clientY});}
function stopBrowserGesture(e){if(e.cancelable)e.preventDefault();}
touchArea.addEventListener('touchstart',e=>{stopBrowserGesture(e);syncTouches(e);beginGesture();},{passive:false,capture:true});
touchArea.addEventListener('touchmove',e=>{stopBrowserGesture(e);syncTouches(e);const pts=[...pointers.values()];if(pts.length===1&&gesture?.kind==='drag'){clamp(gesture.start-(pts[0].x-gesture.x)/geometry.pw*gesture.span,gesture.span);draw();}else if(pts.length>=2&&gesture?.kind==='pinch'){const distance=Math.max(1,Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y)),rect=svg.getBoundingClientRect(),center=((pts[0].x+pts[1].x)/2-rect.left-geometry.left)/geometry.pw,next=gesture.span*gesture.distance/distance;clamp(gesture.start+gesture.anchor*gesture.span-center*next,next);draw();}},{passive:false,capture:true});
touchArea.addEventListener('touchend',e=>{stopBrowserGesture(e);const t=e.changedTouches[0],tap=t&&gesture?.kind==='drag'&&Math.abs(t.clientX-gesture.x)<4;syncTouches(e);if(pointers.size)beginGesture();else gesture=null;if(tap)inspect(t);},{passive:false,capture:true});
touchArea.addEventListener('touchcancel',()=>{pointers.clear();gesture=null;},{passive:false});
for(const type of ['gesturestart','gesturechange','gestureend'])desk.addEventListener(type,stopBrowserGesture,{passive:false,capture:true});
$('mts-type').innerHTML=types.map(t=>'<option value="'+t[0]+'"'+(t[0]===type?' selected':'')+'>'+t[1]+'</option>').join('');$('mts-type').onchange=()=>{type=$('mts-type').value;load();};$('mts-song').onchange=()=>{songId=$('mts-song').value;load();};$('mts-reset').onclick=reset;$('mts-all').onclick=()=>{clamp(0,bars.length);draw();};$('mts-left').onclick=()=>{clamp(start-span*.25,span);draw();};$('mts-right').onclick=()=>{clamp(start+span*.25,span);draw();};$('mts-in').onclick=()=>zoom(.75);$('mts-out').onclick=()=>zoom(1/.75);
$('rr-expand').addEventListener('change',draw);load();if(typeof ResizeObserver!=='undefined')new ResizeObserver(draw).observe(svg);
})();
