const {parseHTML}=require('linkedom');const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const path=require('node:path'),root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');const {document,window}=parseHTML(html);let width=900;
window.HTMLElement.prototype.getBoundingClientRect=window.SVGElement.prototype.getBoundingClientRect=function(){return {width,left:0};};
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return Array.from(this.children).find(o=>o.hasAttribute('selected'))?.getAttribute('value')||this.children[0]?.getAttribute('value');},set(v){for(const o of this.children)o.getAttribute('value')===v?o.setAttribute('selected',''):o.removeAttribute('selected');}});
document.getElementById('rr-data').textContent=require('node:zlib').gunzipSync(Buffer.from(document.getElementById('rr-data').textContent,'base64')).toString();
const db=JSON.parse(document.getElementById('rr-data').textContent),$=id=>document.getElementById(id);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),vm.createContext({document,window,console,Date,Set,Math,Number,JSON,ResizeObserver:class{observe(){}}}));
for(const b of $('rr-tabs').children){$('rr-tabs').onclick({target:b});$('rr-table-chart').value=b.dataset.chart;$('rr-table-chart').onchange();const chart=db.charts[b.dataset.chart],eligible=db.manifest.songs.filter(s=>Object.entries(chart.songs[s.id]||{}).some(([t,p])=>t>=db.manifest.debut&&(!s.release||t>=s.release.slice(0,10))&&Number.isFinite(p.rank)&&p.rank>0));assert.equal($('rr-legend').children.length,eligible.length);assert.equal($('rr-history').querySelectorAll('[data-record-song]').length,eligible.length);assert.deepEqual(Array.from($('rr-legend').children,b=>b.dataset.song),eligible.map(s=>s.id));assert.ok(!/NaN|Infinity|undefined/.test($('rr-chart').innerHTML));}
$('rr-tabs').onclick({target:$('rr-tabs').querySelector('[data-chart="daily"]')});$('rr-table-chart').value='daily';$('rr-table-chart').onchange();assert.match($('rr-chart-sub').textContent,/2024.03.26/);assert.doesNotMatch($('rr-view-label').textContent,/2024.03.26/);
const song=$('rr-legend').children[0];$('rr-legend').onclick({target:song});assert.equal($('rr-legend').children[0].getAttribute('aria-pressed'),'false');assert.match($('rr-legend').children[0].textContent,/＋/);$('rr-show-all').onclick();assert.match($('rr-legend').children[0].textContent,/✓/);
const colors=Array.from($('rr-legend').children,b=>b.querySelector('i').getAttribute('style'));assert.equal(new Set(colors).size,colors.length);
$('rr-hide-all').onclick();assert.equal($('rr-chart').querySelectorAll('path').length,0);$('rr-show-all').onclick();assert.ok($('rr-chart').querySelectorAll('path').length>0);
const wheel=(delta,ctrl=false)=>$('rr-chart').dispatchEvent(Object.assign(new window.Event('wheel',{cancelable:true}),{deltaY:delta,deltaX:0,ctrlKey:ctrl,clientX:450}));
const recent=$('rr-view-label').textContent;wheel(-100);assert.notEqual($('rr-view-label').textContent,recent);const moved=$('rr-view-label').textContent;wheel(-200,true);assert.notEqual($('rr-view-label').textContent,moved);$('rr-fit-view').onclick();assert.match($('rr-view-label').textContent,/2024.03.26/);wheel(-100);assert.match($('rr-view-label').textContent,/2024.03.26/);$('rr-reset-view').onclick();assert.equal($('rr-view-label').textContent,recent);
$('rr-period').onclick({target:$('rr-period').querySelector('[data-period="30"]')});$('rr-full').checked=true;$('rr-full').onchange();assert.match($('rr-chart').innerHTML,/1000/);
width=320;$('rr-full').onchange();assert.match($('rr-chart').getAttribute('viewBox'),/320/);assert.ok(!/NaN|Infinity/.test($('rr-chart').innerHTML));$('rr-chart').onpointerdown?.({clientX:160});assert.match($('rr-detail').textContent,/KST/);
console.log('UI: chart entry filtering, unique colors, selection, wheel pan/zoom, bounds, period reset and mobile inspection pass');

assert.equal($('rr-tooltip').hidden,false);const stamp=$('rr-tooltip').querySelector('strong').textContent.match(/\d{4}\.\d{2}\.\d{2}/)[0].replaceAll('.','-');for(const row of $('rr-tooltip').querySelectorAll('[data-tip-song]')){const point=db.charts.daily.songs[row.dataset.tipSong]?.[stamp];if(point?.rank!=null)assert.equal(row.querySelector('b').textContent,point.rank+'위');}assert.match($('rr-tooltip').textContent,/KST/);assert.ok($('rr-tooltip').querySelectorAll('.rr-tip-row').length>0);assert.ok(Array.from($('rr-chart').querySelectorAll('path')).every(p=>p.getAttribute('stroke-width')==='1.1'));$('rr-chart').onpointerleave();assert.equal($('rr-tooltip').hidden,true);
const chartTitle=$('rr-chart-title').textContent;$('rr-table-chart').value='top100';$('rr-table-chart').onchange();assert.equal($('rr-chart-title').textContent,chartTitle);assert.match($('rr-table-title').textContent,/TOP100/);
for(const option of $('rr-table-chart').children){$('rr-table-chart').value=option.getAttribute('value');$('rr-table-chart').onchange();const best=Array.from($('rr-history').querySelectorAll('[data-record-song]'),tr=>Number(tr.children[2].textContent.replace('위',''))||Infinity);assert.deepEqual(best,[...best].sort((a,b)=>a-b));}
console.log('UI: thin lines, timestamp tooltip, independent table chart selection and peak ordering pass');

for(const type of ['top100','hot100-d30','hot100-d100']){ $('rr-tabs').onclick({target:$('rr-tabs').querySelector('[data-chart="'+type+'"]')});const ticks=()=>Array.from($('rr-chart').querySelectorAll('text[x="40"]'),el=>Number(el.textContent));assert.deepEqual(ticks(),[1,20,40,60,80,100]);$('rr-hide-all').onclick();assert.deepEqual(ticks(),[1,20,40,60,80,100]);$('rr-show-all').onclick();assert.deepEqual(ticks(),[1,20,40,60,80,100]);}console.log('UI: TOP100 and both HOT100 axes stay at 1–100 including empty selection');

for(const type of ['daily','weekly','monthly','yearly']){$('rr-tabs').onclick({target:$('rr-tabs').querySelector('[data-chart="'+type+'"]')});assert.ok($('rr-top100-line'));assert.equal($('rr-top100-line').getAttribute('stroke-width'),'3');assert.ok(Number.isFinite(Number($('rr-top100-line').getAttribute('y1'))));}
$('rr-tabs').onclick({target:$('rr-tabs').querySelector('[data-chart="daily"]')});$('rr-mode').onclick({target:$('rr-mode').querySelector('[data-mode="candle"]')});assert.ok($('rr-chart').querySelector('[data-candle]'));assert.ok($('rr-legend').hidden);$('rr-chart').onpointerdown({clientX:160});assert.match($('rr-tooltip').textContent,/첫 순위.*마지막 순위.*최고 순위.*최저 순위/);assert.match($('rr-tooltip').textContent,/진입 기록/);const dates=$('rr-tooltip').querySelector('strong').textContent.match(/\d{4}\.\d{2}\.\d{2}/g).map(x=>x.replaceAll('.','-')),id=$('rr-candle-song').value,observed=Object.entries(db.charts.daily.songs[id]).filter(([t,p])=>t>=dates[0]&&t<=dates[1]&&p.rank!=null).sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[1].rank);assert.deepEqual(Array.from($('rr-tooltip').querySelectorAll('b'),b=>parseInt(b.textContent)),[observed[0],observed.at(-1),Math.min(...observed),Math.max(...observed)]);assert.ok(!/NaN|Infinity|undefined/.test($('rr-chart').innerHTML));$('rr-mode').onclick({target:$('rr-mode').querySelector('[data-mode="line"]')});assert.equal($('rr-legend').hidden,false);console.log('UI: 100-rank reference lines and observed-record candle mode pass');
